[package]
name = "tangara-cli"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "tangara"
path = "src/main.rs"

[dependencies]
# project crates
tangara-lib = { workspace = true }

# workspace deps
thiserror = { workspace = true }
futures = { workspace = true }

# general deps
console = "0.15"
indicatif = "0.17"
thread-executor = "0.1.0"
structopt = "0.3.26"

